CREATE TABLE process_completions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            VARCHAR(64)  NOT NULL REFERENCES orders (id),
    process_instance_id VARCHAR(64)  NOT NULL,
    completed_by        VARCHAR(255) NOT NULL,
    completed_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_process_completions_process_instance_id UNIQUE (process_instance_id)
);

CREATE INDEX idx_process_completions_order_id ON process_completions (order_id);
